### PR TITLE
fix typescript 'browse' tool to new entrystream flag

### PR DESCRIPTION
**Pull request by evmar**
The flag to make it consume JSON changed.

### CODE REVIEW

**Comment by evmar** [comment]
Neither the 0.0.26 release nor the 0.0.27 releases support --read_format=json.  What am I missing?

**Comment by schroederc** [comment]
It's on `master` and will be in the upcoming 0.0.28 release.

**Comment by evmar** [comment]
I will just build a wrapper for now so I can run the test suite.

```
package main

import (
	"os"
	"syscall"
)

func main() {
	for i, arg := range os.Args {
		if arg == "--read_format=json" {
			os.Args[i] = "--read_json"
		}
	}
	os.Args[0] = "entrystream.real"
	syscall.Exec(os.Args[0], os.Args, nil)
}
```

**Comment by schroederc** [comment]
You can also just build the tool: `go get -u kythe.io/kythe/go/platform/tools/entrystream`

**Pull request closed without merging**
