### PR TITLE
Make maven/gradle extractors default to using kzip

### LINKED ISSUE #3059: Maven/gradle extraction should port to .kzip
Still writing .kindex for now.

### PR DESCRIPTION
**Pull request by danielmoy-google**
Also remove an unused method in java extractor.

Fixes #3059

### CODE REVIEW

**Comment by creachadair** [comment]
#3069 may wind up preventing this from working until it is fixed.

**Comment by danielmoy-google** [comment]
> #3069 may wind up preventing this from working until it is fixed.

Noted, though we might be fine with that since there's a big enough stack of work to be done on just extracting before any indexing is done.

Also this just affects the default, we can always use the config json to just specify a different value for KYTHE_OUTPUT_FILE, and it'd be set accordingly.

**Comment by creachadair** [comment]
> Also this just affects the default, we can always use the config json to just specify a different value for KYTHE_OUTPUT_FILE, and it'd be set accordingly.

Yeah, so maybe for now we should include the setting, but use `.kindex` for  suffix, just so the fallback continues to work?

**Comment by creachadair** [comment]
Per our offline discussion: A fix for #3069 is in progress, and nothing important depends on the default right now, so we can go ahead.

**Pull request merged**
